name: multifit
channels:
    - defaults
    - conda-forge
dependencies:
    - python==3.9.*
    - numpy<2.1.0
    - matplotlib
    - scipy
    - custom-inherit
    - Deprecated
    - pip
    -   pip:
            - mpyez
