name: multifit
channels:
    - defaults
    - conda-forge
dependencies:
    - python==3.9.*
    - numpy<2.1.0
    - matplotlib
    - scipy
    - statsmodels
    - custom-inherit
    - Deprecated
    - seaborn
    - pandas
    - pytest
    - pytest-cov
    - astropy
    - jupyter
    - notebook
    - build
    - memory_profiler
    - sphinx>8
    - docutils<0.21
    - sphinx-rtd-theme
    - pydata-sphinx-theme
    - sphinx-copybutton
    - sphinxcontrib-napoleon
    - numpydoc
    - nbsphinx
    - nbsphinx-link
    - sphinx-gallery
    - sphinx-autobuild
    - mypy
    - nox
    - uv
    - types-deprecated
    - scipy-stubs
    - pylint
    - black
    - pip
    -   pip:
            - mpyez
            - optype
