name: multifit
channels:
    - conda-forge
    - nodefaults
dependencies:
    - python==3.10.*
    - numpy<2.0.0
    - matplotlib
    - scipy
    - custom-inherit
    - Deprecated
    - pip
    -   pip:
            - mpyez
